### ISSUE TITLE
What is the purpose of this?

### ISSUE THREAD

**Issue by daFreeMan** [pallebone/UnifiUnraidReborn#2]
What is the purpose of this docker on my UNRAID server? 

I've got a UniFi router, and I've got the UniFi console web page open quite frequently. What does this buy me that I might not get by reviewing that page? Is there extra convenience? Stats gathering? 

I'd love to install this if it's going to bring me some extra goodies, but I don't know what those goodies might be.

Thanks!

**Comment by pallebone** [comment]
If you own a unifi gateway device or official harware that runs the unifi software there is no benefit.

Many users own access points or switches but do not want to buy a unifi router (ie might use opnsense etc).

In this case the controller software must be run on docker eg: on unraid.

Kind regards
Pete

**Comment by mkono87** [comment]
> If you own a unifi gateway device or official harware that runs the unifi software there is no benefit.
> 
> Many users own access points or switches but do not want to buy a unifi router (ie might use opnsense etc).
> 
> In this case the controller software must be run on docker eg: on unraid.
> 
> Kind regards Pete

I think he is asking why call it Reborn if its just like any other docker based unifi-controller?

**Comment by pallebone** [comment]
> I think he is asking why call it Reborn if its just like any other docker based unifi-controller?

Linuxserver.io is killing off the old controller that had mongodb embedded into it in January 2024. It will then no longer receive updates. This is replacing that for unraid users (possibly) and is being tested prior to Jan 2024 (ie now).

Your migration path is do what linuxserver.io want - run 2 containers (mongodb is seperate) or come up with an alternative (this is what I am doing).

**Comment by shaunvis1** [comment]
> > I think he is asking why call it Reborn if its just like any other docker based unifi-controller?
> 
> Linuxserver.io is killing off the old controller that had mongodb embedded into it in January 2024. It will then no longer receive updates. This is replacing that for unraid users (possibly) and is being tested prior to Jan 2024 (ie now).
> 
> Your migration path is do what linuxserver.io want - run 2 containers (mongodb is seperate) or come up with an alternative (this is what I am doing).

I'm currently using the linuxserver version. I was annoyed by their message killing it off and don't have the time or patience to set up a database docker just to run unifi controller. 

I'm hoping this is going to be a long term supported docker so I can migrate to this.

**Comment by pallebone** [comment]
We are trying our best, please be patient it is not ready yet... we have until January. Everyone wants a solution, this is mostly working, with a few things not 100% so please continue to use linuxserver.io in the meantime and check back. 

Also this is for UNRAID, there is a pure docker image already ready to be used here:
https://hub.docker.com/r/11notes/unifi 

If you run your own docker deployment on linux eg: ubuntu/debian and so on.
Just the UNRAID part is still being fixed up.

**Comment by pallebone** [comment]
@11notes docker github is here: https://github.com/11notes/docker-unifi

He is very helpful and awesome, and his image works already on pure linux as I mentioned. 
When its working well on Unraid I will post here again. Its mostly working, just some issues to resolve.

**Comment by shaunvis1** [comment]
> We are trying our best, please be patient it is not ready yet... we have until January. Everyone wants a solution, this is mostly working, with a few things not 100% so please continue to use linuxserver.io in the meantime and check back.
> 
> Also this is for UNRAID, there is a pure docker image already ready to be used here: https://hub.docker.com/r/11notes/unifi
> 
> If you run your own docker deployment on linux eg: ubuntu/debian and so on. Just the UNRAID part is still being fixed up.

I really appreciate the work on this, I have it pinned and was just waiting for it to be good to go. 

I use Unraid and prefer the easy docker rollout like this so I'm happy to wait  just glad you're doing it! Thanks!

**Comment by pallebone** [comment]
Dont worry. We will get something working by the deadline.

**Comment by ultimz** [comment]
Thanks for working on this @pallebone - appreciate it. I will definitely migrate to this docker (for Unraid) once it's ready.

**Comment by pallebone** [comment]
I will be creating a thread on the unraid forum somtime this weekend when it is out of canary and into alpha since it works now if some permissions are changed with ssh on the docker directory to accommodate.

**Comment by pallebone** [comment]
We need testing if possible: https://forums.unraid.net/topic/147455-support-unifi-controller-unifi-unraid-reborn/

**Comment by 11notes** [comment]
Sorry, missed the discussion. What do you need? I can build the image as 99:100 if that helps?

**Comment by pallebone** [comment]
> Sorry, missed the discussion. What do you need? I can build the image as 99:100 if that helps?

Its quite alright. I will open a ticket on your github page explaining what we found and we can try think of the best solution together without making any rash changes to ensure we carefully resolve the problem in an ideal way. At this time there is no reason to rush :)

**Comment by pallebone** [comment]
Closing ticket as we now have a forum thread here if you need to ask further questions:
https://forums.unraid.net/topic/147455-support-unifi-controller-unifi-unraid-reborn/

**Comment by daFreeMan** [comment]
Sorry, late in getting back to my own party...

> I think he is asking why call it Reborn if its just like any other docker based unifi-controller?

No, actually, I wasn't sure exactly what the purpose of these UniFi dockers is, including the LS.IO one. 

Since I do have a UniFi router, I've got the software already and have no need for this. I thought that maybe the dockers added something extra that wasn't in the official Ubiquiti software.

**Comment by mkono87** [comment]
> Sorry, late in getting back to my own party...
> 
> > I think he is asking why call it Reborn if its just like any other docker based unifi-controller?
> 
> No, actually, I wasn't sure exactly what the purpose of these UniFi dockers is, including the LS.IO one.
> 
> Since I do have a UniFi router, I've got the software already and have no need for this. I thought that maybe the dockers added something extra that wasn't in the official Ubiquiti software.

Gotcha, yeah its used for people such as myself who dont use Unifi firewalls. I only use the switches and APs, I actually switched to this one now becuase LS decided to seperate mongodb from the container so I ditched it as I dont want to run two containers just for unifi.
