### ISSUE TITLE
HTTP 404 - Not Found after starting container

### ISSUE THREAD

**Issue by cpsmith516** [pallebone/UnifiUnraidReborn#4]
Unraid -
Container shows as started (unhealthy), when trying to access webui receive HTTP 404. Logs window is blank. 

Attempted force update of container image, issue persists. Where can I collect logs to upload for help with this?

**Comment by pallebone** [comment]
Do not use webui button on a br.x network, instead use the ip address:
in your case use https://192.168.4.100:8443 in a browser on the same network.

Should open the web UI.

Please post a screenshot of "started, unhealthy" so I can see what you are talking about.

**Comment by cpsmith516** [comment]
the 4.100 IP was an attempt to see if the network was the issue. It has since been set back to bridge mode. I also just tried removing the appdata folder and letting it recreate fresh. 

After having the appdata folder recreate itself the new error is "ERR_CONNECTION_REFUSED" from browser. 

here is the screenshot as requested - this is from the freshly recreated container. It sits in this state for a while and then changes to say (unhealthy) out beside it.  
![image](https://github.com/pallebone/UnifiUnraidReborn/assets/33228605/70de5b15-5f11-4eb0-9574-a8423b1116ad)

**Comment by cpsmith516** [comment]
![image](https://github.com/pallebone/UnifiUnraidReborn/assets/33228605/3219b606-e726-4924-b6b8-37911404079b)

**Comment by cpsmith516** [comment]
Log displays: 
WARN Unable to load properties from '/usr/lib/unifi/data/system.properties' - /usr/lib/unifi/data/system.properties (No such file or directory)

**Comment by pallebone** [comment]
Strange. Can you post the docker run output again ?

eg this stuff you posted before

”
docker run
-d
--name='unifi-controller-reborn'
--net='br0.4'
--ip='192.168.4.100'
-e TZ="America/Chicago"
-e HOST_OS="Unraid"

And so on. Also can you check the directory permissions for the reborn container?

**Comment by pallebone** [comment]
To check permissions will be command like:

cd /mnt/user/appdata/
ls -asxhl

Output should be like:

0 drwxr-xr-x 1 nobody users 222 Dec  7 13:26 unifi-controller-reborn/

**Comment by cpsmith516** [comment]
docker run
  -d
  --name='unifi-controller-reborn'
  --net='bridge'
  -e TZ="America/Chicago"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="unraid"
  -e HOST_CONTAINERNAME="unifi-controller-reborn"
  -e 'MEM_LIMIT'='4096'
  -e 'MEM_STARTUP'='2048'
  -e 'UMASK'='002'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='https://[IP]:[PORT:8443]'
  -l net.unraid.docker.icon='https://user-images.githubusercontent.com/11403137/277435263-1b01facd-1b15-4ba7-9495-e709c291d67f.jpg'
  -p '8443:8443/tcp'
  -p '3478:3478/udp'
  -p '10001:10001/udp'
  -p '8080:8080/tcp'
  -p '1900:1900/udp'
  -p '8843:8843/tcp'
  -p '8880:8880/tcp'
  -p '6789:6789/tcp'
  -p '5514:5514/udp'
  -v '/mnt/user/appdata/unifi-controller-reborn':'/unifi/var':'rw'
  --memory=8G '11notes/unifi:7.5.187-unraid'
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
8553a5cfb35af5ac6812f8424461ec0392b5474b6de1173c4c6908578d7c8c7d

The command finished successfully!

**Comment by cpsmith516** [comment]
0 drwxr-xr-x 1 nobody users  196 Dec  7 14:25 unifi-controller-reborn/

**Comment by cpsmith516** [comment]
I was able to get it to work with a total rebuild of the docker container, and no appdata folders present, then restored my unifi configuration to that fresh instance.

**Comment by pallebone** [comment]
Interesting. Did you not start fresh somehow when you first started? I am not clear how you deployed the image but it was not freshly built in the first instance. Something must have gone wrong during this stage.

**Comment by cpsmith516** [comment]
I did the same thing 2 days ago, fresh install, restored backup. Today I wasn't able to login to it at all, and when I rebooted the container it went into that unhealthy state and wouldn't completely start up. Subsequent reinstalls of the container image (while keeping my appdata with the restored backup) kept the same problem. 

I suspect something is happening to the container when I restore my backup (which granted is from a previous version of Unifi).  

Is there a way I can run the upgrade for Unifi in the console of the container to get it back to 8.0 after I restore my 7.x backup to it?

**Comment by pallebone** [comment]
Yes please setup the container and check it is working. Then when you are happy please stop the container and wait 60 seconds and start it again. Check everything is still working. 

If all is ok at this point then edit the container and change the tag to:
11notes/unifi:8.0.7-unraid

Kind regards,
P

**Comment by cpsmith516** [comment]
Ok, back on 8.0.7. Thanks for that trick. Should I remove the tag now that it's updated?

**Comment by pallebone** [comment]
No that tag is what defines what version of the unifi controller the docker must run. If you remove it then it wont know how to start. 

Let me know if you need any further help, or feel free to close this issue if you dont :)

**Comment by cpsmith516** [comment]
Issue resolved
