### ISSUE TITLE
Please check Disclaimers on new build about disabling telemetry!

### ISSUE THREAD

**Issue by 11notes** [pallebone/UnifiUnraidReborn#5]
I have seen on Reddit that a lot of people do not deactivate telemetry on Unifi, so I added the deactivation by default. It's written in the disclaimer of the image:

## Disclaimers
* <sup>1</sup> This image will automatically disable anonymous telemetry collected by Ubiquiti by adding a flag (`config.system_cfg.1=system.analytics.anonymous=disabled`) to each sites `config.properties`. You will still have to disable telemetry in the global settings too, to disable *all* telemetry. You can check your telemetry status by SSH’ing into an access point and checking ` grep analytics /tmp/system.cfg`, the output should both read `disabled`.

**Comment by pallebone** [comment]
Ok thank you

**Comment by pallebone** [comment]
I tested this and it is untrue on tag [8.0.26-unraid]:
![Screenshot from 2024-02-22 15-21-32](https://github.com/pallebone/UnifiUnraidReborn/assets/11403137/c62de7b2-2a47-468f-8c69-fe9b7a415946)

**Comment by pallebone** [comment]
In a few days unifi will release a new controller version, can we test this again before releasing that as a final image?

**Comment by 11notes** [comment]
> I tested this and it is untrue on tag [8.0.26-unraid]: ![Screenshot from 2024-02-22 15-21-32](https://private-user-images.githubusercontent.com/11403137/307138864-c62de7b2-2a47-468f-8c69-fe9b7a415946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NDE4NzIsIm5iZiI6MTcwODY0MTU3MiwicGF0aCI6Ii8xMTQwMzEzNy8zMDcxMzg4NjQtYzYyZGU3YjItMmE0Ny00NjhmLThjNjktZmU5YjdhNDE1OTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDIyMzkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0N2Q1MGY4MjRkOTc0OWExN2JjMjVkZTU1MWFmZDQwNzE4NGJlZjk4ZmRlNDZiN2RiYWJlNmMxZWZkZjE2OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qYJ0qRfqcH0ohh7JPNs4ddGFnZKSqDqy_UUi0w9ILKU)

Read the disclaimer again:

## Disclaimers
* <sup>1</sup> This image will autom..... **You will still have to disable telemetry in the global settings too, to disable *all* telemetry.** ........n your DNS blocker.
