### ISSUE TITLE
Updating to the latest Unifi version

### ISSUE THREAD

**Issue by MrDecepticon** [pallebone/UnifiUnraidReborn#6]
When I initially installed your docker it installed an older version (7.something) and to get it to install the latest we had to add "11notes/unifi:8.0.7-unraid" to the repository field.  

Is there a repository entry that will always pull the latest build?

**Comment by pallebone** [comment]
No, it is purposefully designed to not have that, by design. You are expected to manage upgrades as it appropriate for your site.

**Comment by PRO50347** [comment]
so how do we update to the new 8 .x.x ? im new to unraid

**Comment by pallebone** [comment]
> so how do we update to the new 8 .x.x ? im new to unraid

Are you already using unifi reborn on unraid? If so then you just edit the docker and change the tag to a valid tag AFTER TAKING A BACKUP. A list of valid tags are on the unraid forum post.

**Comment by pallebone** [comment]
No response. Closing ticket.
